title: AnhNguyenNote
description: Ghi chú cá nhân từ Zettel Notes
remote_theme: riggraz/no-style-please

# Các plugin cần thiết để chạy trên GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

# Cấu hình menu điều hướng (Tùy chỉnh theo ý bạn)
navigation:
  - { title: "Trang chủ", url: "/" }
